### PR TITLE
Add esplora plugin from lvaccaro

### PR DESCRIPTION
**Pull request by jsarenik**
https://github.com/lightningamp/esplora_clnd_plugin

### CODE REVIEW

**Comment by jsarenik** [comment]
The force-push history will be tracked in this fake PR. So far my local reflog says this:

```
$ git reflog | grep esplora
70977a4fb HEAD@{0}: checkout: moving from jsn/esplora to master
33f2863b8 HEAD@{1}: commit (amend): Add esplora plugin from lvaccaro
5312d5ff7 HEAD@{2}: rebase finished: returning to refs/heads/jsn/esplora
5312d5ff7 HEAD@{3}: rebase: Add esplora plugin from lvaccaro
c5a8d615d HEAD@{5}: checkout: moving from master to jsn/esplora
ff090ecfe HEAD@{7}: checkout: moving from jsn/esplora to master
c5a8d615d HEAD@{8}: rebase finished: returning to refs/heads/jsn/esplora
c5a8d615d HEAD@{9}: rebase: Add esplora plugin from lvaccaro
5398d2ded HEAD@{11}: checkout: moving from master to jsn/esplora
66b2bb9a9 HEAD@{13}: checkout: moving from jsn/esplora to master
5398d2ded HEAD@{14}: commit: Add esplora plugin from lvaccaro
66b2bb9a9 HEAD@{15}: checkout: moving from master to jsn/esplora
```

**Comment by jsarenik** [comment]
The steps I use to update this branch are:

```
cd ~/src/lightning
git checkout master
git pull
git push jsn
git checkout jsn/esplora
git rebase master
git push --force jsn
```

**Comment by jsarenik** [comment]
The tests are currently broken by this:

```
lightningd-1: 2020-12-13T16:57:49.946Z **BROKEN** plugin-esplora: Plugin marked as important, shutting down lightningd!
```

**Comment by jsarenik** [comment]
It corrently throws a compilation error:

```
plugins/esplora.c: In function ‘main’:
plugins/esplora.c:776:12: error: passing argument 2 of ‘plugin_main’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  776 |      argv, init, PLUGIN_STATIC, false, NULL, commands,
      |            ^~~~
      |            |
      |            void (*)(struct plugin *, const char *, const jsmntok_t *) {aka void (*)(struct plugin *, const char *, const struct <anonymous> *)}
In file included from plugins/esplora.c:22:
./plugins/libplugin.h:280:20: note: expected ‘const char * (*)(struct plugin *, const char *, const jsmntok_t *)’ {aka ‘const char * (*)(struct plugin *, const char *, const struct <anonymous> *)’} but argument is of type ‘void (*)(struct plugin *, const char *, const jsmntok_t *)’ {aka ‘void (*)(struct plugin *, const char *, const struct <anonymous> *)’}
  280 |      const char *(*init)(struct plugin *p,
      |      ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
  281 |            const char *buf,
      |            ~~~~~~~~~~~~~~~~
  282 |            const jsmntok_t *),
      |            ~~~~~~~~~~~~~~~~~~
```

**Comment by jsarenik** [comment]
Compilation error fixed:

```diff
diff --git a/plugins/esplora.c b/plugins/esplora.c
index 2657c345e..6ab1fb27b 100644
--- a/plugins/esplora.c
+++ b/plugins/esplora.c
@@ -671,7 +671,7 @@ static bool configure_esplora_with_network(const char *network,
 	return false;
 }
 
-static void init(struct plugin *p, const char *buffer, const jsmntok_t *config)
+static const char *init(struct plugin *p, const char *buffer, const jsmntok_t *config)
 {
 	const jsmntok_t *proxy_tok = json_get_member(buffer, config, "proxy");
 	if (proxy_tok) {
@@ -719,6 +719,7 @@ static void init(struct plugin *p, const char *buffer, const jsmntok_t *config)
 	if (proxy_conf->proxy_enabled && !esplora->proxy_disabled)
 		plugin_log(p, LOG_INFORM, "proxy configuration %s:%d",
 			   proxy_conf->address, proxy_conf->port);
+	return NULL;
 }
 
 static struct esplora *new_esplora(const tal_t *ctx)
```

**Comment by jsarenik** [comment]
@vincenzopalazzo FYI ^^ (see above)

**Comment by vincenzopalazzo** [comment]
@jsarenik hello, I will take a look to compile it in my dev environment and I will return back here when I have some feedback at the moment it looks good. What do you think @lvaccaro?

Update: I missed this update inside the lightning https://github.com/ElementsProject/lightning/commit/27c006f7aa3ea7a5a38bd68d06c0b60614f0ad3c.

ack https://github.com/jsarenik/lightning/pull/1/commits/157b4c4208e588547bdae8b74377d93969bed410

**Comment by jsarenik** [comment]
In the latest Lightning talk on Blockstream's YouTube, Rusty mentions this plugin: https://github.com/lightningd/plugins/tree/master/sauron

@lvaccaro Do you have any experience with sauron? I have not tried it at all yet.

**Comment by lvaccaro** [comment]
Sauron plugin works pretty good, I took it as reference when I wrote esplora plugin in C. Sauron 's author also made some contributions in C esplora plugin to make it work great.

**Comment by vincenzopalazzo** [comment]
Hi there!

There are a couple of difference at this moment with esplora and sauron, that are reported below

-  Sauron resolve the esplora fee problem with the following [hack](https://github.com/lightningd/plugins/blob/a7a0007dcee1fcf3cc401ca83663a66b678e07d3/sauron/sauron.py#L175), esplora use the same approach of c-lightning [look here](https://github.com/lightningamp/esplora_clnd_plugin/blob/12c7309816552a16423aced482b7a17ff93105cb/esplora.c#L417)
- esplora retry the connect if the code is not 200 with the [following code](https://github.com/lightningamp/esplora_clnd_plugin/blob/12c7309816552a16423aced482b7a17ff93105cb/esplora.c#L126) because the plugin needs to run on mobile devices where the connection is not available each time, sauron a lib config that I don't know if it is the same, for more info you can look [here](https://github.com/lightningd/plugins/blob/a7a0007dcee1fcf3cc401ca83663a66b678e07d3/sauron/sauron.py#L27)
- And the last difference is that sauron take the config from the command line and esplora is able to auto config from the clightning info, but it is not a difference, it is only my fault that I proposed this change in the c-lightning side and I didn't work enough to update also the plugin sauron. My fault :)

p.s: From my experiments Both esplora and sauron share the same problems with the esplora API (at the moment)

**Comment by vincenzopalazzo** [comment]
Hello @jsarenik, if you want try to connect over the testnet network with lightning and esplora plugin you can use this node https://1ml.com/testnet/node/03b1330add0c75e0b2e1401dc61028a3d2351b9fef439d703f7ff71f3a182f9192 

This node is managed by me and also it is running over an experimental plugin where I'm making some experiments to improve the esplora plugin.

**Comment by jsarenik** [comment]
> Hello @jsarenik, if you want try to connect over the testnet network with lightning and esplora plugin you can use this node https://1ml.com/testnet/node/03b1330add0c75e0b2e1401dc61028a3d2351b9fef439d703f7ff71f3a182f9192
> 
> This node is managed by me and also it is running over an experimental plugin where I'm making some experiments to improve the esplora plugin.

@vincenzopalazzo Done. and I also did a `keysend 500000` your way (unsolicited payment :)

**Comment by vincenzopalazzo** [comment]
Oh @jsarenik, oh Rusty yesterday said "Wow lightning sometimes works" :)

I suppose that my node is up because I didn't check this morning. I'm testing [btcli4j](https://github.com/clightning4j/btcli4j) and sometimes I receive some exception server side

**Comment by jsarenik** [comment]
Now that I finally have [a simple script](https://github.com/lightningd/plugins/issues/112#issuecomment-818789990) I am thinking about discontinuing this branch. What do you think @lvaccaro and @vincenzopalazzo? Thank you!

**Comment by vincenzopalazzo** [comment]
@jsarenik concept ack for the script. It looks good to me, and I will test it on my local machine soon.

>I am thinking about discontinuing this branch

This is up to you :)

**Pull request closed without merging**
